<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 m-auto">
      <div class="card card-body">
        <h1 class="text-center mb-3">
          <i class="fas fa-sign-in-alt"></i> Login
        </h1>
        <?php if (Session::getError() !== null) : ?>
          <div class="alert alert-danger" role="alert">
            <?= Session::getError() ?>
          </div>
        <?php endif; ?>
        <?php if (!Session::isConnected()) : ?>
          <form method='post' action="login">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" id="email" name="email" class="form-control" placeholder="Enter email" />
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" id="password" name="password" class="form-control" placeholder="Enter password" />
            </div>
            <button type="submit" class="btn btn-primary btn-block">Login</button>
          </form>
          <p class="lead mt-4">No Account? <a href="signUp">Sign up</a></p>
      </div>
    <?php else : ?>
      <div class="alert alert-success" role="alert">
        <?= 'Vous êtes connecté ! ' ?>
      </div>
    <?php endif ?>
    </div>
  </div>
</div>