<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>National Golf Resort</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body style='box-sizing:border-box; margin:0; display:flex; flex-direction:column'>
    <div class="container">
        <header style="height:300px; background-image: url('./assets/header.jpg'); background-position:center; " class="text-white  d-flex flex-wrap align-items-center justify-content-around py-3 mb-3 border-bottom">
            <p class="display-3 text-center">National Golf Resort</p>
            <nav class="navbar">
                <ul class=" nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="text-white nav-link px-2 link-dark">Home</a></li>
                    <li><a href="blog" class="text-white nav-link px-2 link-dark">Le Blog</a></li>
                </ul>
                <div class="d-flex col-md-3 text-end list-unstyled">
                    <!--TODO conditionner selon la session utiliser-->
                    <li><a style="width:90px" href="login" class="btn btn-outline-primary text-white  ">Login</a></li>
                    <li><a style="width:90px" href="signUp" class="btn btn-primary text-white ">Sign-Up</a></li>
                    <li><a style="width:90px" href="logout" class="btn btn-secondary">Logout</a></li>
                    <li><img src="./assets/user.png" class="rounded-circle" height="40" width="40" alt="Avatar"></li>
                    <li><a class="btn btn-primary" href="userSpace">Mon compte</a></li>
                </div>
            </nav>
        </header>
    </div>

    <main style="flex-grow:1">;
        <?php include $content ?>
    </main>

    <footer class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="https://mdbootstrap.com/">Nos Mentions Légales</a>
        </div>
        <!-- Copyright -->
    </footer>