<div class="container mt-5">
    <h1 class="text-center">Bienvenue sur le blog</h1>
    <div id="posts" class="mt-5">
        <!-- TODO inserer les post via blog.php -->

        <?php foreach ($posts as $post) { ?>
            <div class="card mb-3">
                <div class="card-header">
                    <?php echo $post['title']; ?>
                </div>
                <div class="card-body">
                    <?php echo $post['content']; ?>
                </div>
                <div class="card-footer text-muted">
                    Posté par utilisateur <?php echo $post['user_id']; ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>