<?php require './controller/blog.php' ?> <!-- TODO ne pas repeter cette ligne -->


<div class="container my-5 mb-5">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title text-center mb-4"><?= $posts['title'] ?></h2>
            <p><?= $posts['content'] ?></p>
        </div>
        <div class="card-footer text-muted text-center">
            Posté par <?= $posts['name'] ?> le <?= date('d/m/Y', strtotime($posts['created_at'])) ?>
        </div>
    </div>
</div>