<div class="container">
    <h1>Les 3 étapes d'apprentissage du Golf !</h1>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="./assets/Golf1.jpg" class="card-img-top" alt="Image 1">
                    <div class="card-body">
                        <h5 class="card-title">Le planter de baton</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum blanditiis nam temporibus amet optio, fugit ipsa et dolores iusto quibusdam voluptate. Veniam, dolor!</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="./assets/shoot.jpg" class="card-img-top" alt="Image 2">
                    <div class="card-body">
                        <h5 class="card-title">Le shoot</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus natus eligendi sint voluptatibus eius dicta.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="./assets/putt.jpg" class="card-img-top" alt="Image 3">
                    <div class="card-body">
                        <h5 class="card-title">Le Putt</h5>
                        <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae consequuntur ex quam accusamus laborum, adipisci praesentium. Optio vitae consequatur placeat, aspernatur velit maiores expedita enim error cumque asperiores, dolore distinctio?</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>